---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)
library(tidyverse)
```

## Current Fashion Trends

```{r}
url <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vRjigrDOcIOR_WeQsYRI1E2MOcQkZM_ui3qDMLCryvt8CVi_WQgvkgQPXoOhLCNqU_NumuTcSlDfWUd/pub?gid=93030082&single=true&output=csv"
logged_data <- read_csv(url)

latest_data <- rename(logged_data, 
  cool_people_seen = `How many people do you see a day where you think "Wow that person looks cool"?`,
  current_fashion = `How much do you like the current fashion trends on campus?`,
  prefer_trends = `Which option would you most prefer?`
)

curr_fashion <- latest_data$current_fashion
current_fashion_average <- mean(curr_fashion, na.rm = TRUE)
current_fashion_minimum <- min(curr_fashion, na.rm = TRUE)

latest_data %>%
  ggplot() +
  geom_bar(aes(x = prefer_trends))

latest_data %>%
  ggplot() +
  geom_bar(aes(x = cool_people_seen))

current_fashion_minimum
```

The average rating for current fashion trends is **`r round(current_fashion_average, 2)`**.  
The lowest rating given was **`r current_fashion_minimum`**.  

---

```{css}
h2 {
  color: navy;
}

p {
  font-size: 16px;
  line-height: 1.5;
}
```
